import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/custom/Navbar";
import SideMenu from "@/components/custom/SideMenu";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-zinc-900 h-screen max-h-screen">
      {" "}
      <Navbar />
      <div className="h-5/6 w-1/5">
        {" "}
        <SideMenu />
      </div>
      {children}
    </div>
  );
}
